<a href="https://colab.research.google.com/github/manthanawgan/Titanic-Survival-Prediction/blob/main/Titanic_Survival_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [75]:
df = pd.read_csv('/content/train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Embarked:

The port where the passenger boarded the ship:

C → Cherbourg

Q → Queenstown

S → Southampton

In [76]:
print(df.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [77]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [78]:
df['Has_Cabin'] = df['Cabin'].notnull().astype(int)  # 1 if cabin is known, 0 if NaN
print(df.groupby('Has_Cabin')['Survived'].mean())

Has_Cabin
0    0.299854
1    0.666667
Name: Survived, dtype: float64

In [79]:
df['Deck'] = df['Cabin'].str[0]  # Extract first letter of Cabin
print(df.groupby('Deck')['Survived'].mean().sort_values())

Deck
T    0.000000
A    0.466667
G    0.500000
C    0.593220
F    0.615385
B    0.744681
E    0.750000
D    0.757576
Name: Survived, dtype: float64

In [80]:
df.drop(columns=['Name','Ticket'],inplace=True)
df.drop(columns=['PassengerId'],inplace=True)

In [81]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Has_Cabin,Deck
0,0,3,male,22.0,1,0,7.2500,NaN,S,0,NaN
1,1,1,female,38.0,1,0,71.2833,C85,C,1,C
2,1,3,female,26.0,0,0,7.9250,NaN,S,0,NaN
3,1,1,female,35.0,1,0,53.1000,C123,S,1,C
4,0,3,male,35.0,0,0,8.0500,NaN,S,0,NaN

In [82]:
df.tail(5)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Has_Cabin,Deck
886,0,2,male,27.0,0,0,13.00,NaN,S,0,NaN
887,1,1,female,19.0,0,0,30.00,B42,S,1,B
888,0,3,female,NaN,1,2,23.45,NaN,S,0,NaN
889,1,1,male,26.0,0,0,30.00,C148,C,1,C
890,0,3,male,32.0,0,0,7.75,NaN,Q,0,NaN

Test data

In [83]:
df2 = pd.read_csv('/content/test.csv')
df2.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [84]:
df2.drop(columns=['Name','Ticket'],inplace=True)

In [85]:
df2.head()

   PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0          892       3    male  34.5      0      0   7.8292   NaN        Q
1          893       3  female  47.0      1      0   7.0000   NaN        S
2          894       2    male  62.0      0      0   9.6875   NaN        Q
3          895       3    male  27.0      0      0   8.6625   NaN        S
4          896       3  female  22.0      1      1  12.2875   NaN        S

In [93]:
print(df.tail(5))
print(df2.tail(5))

     Survived  Pclass     Sex   Age  SibSp  Parch   Fare Cabin Embarked  \
886         0       2    male  27.0      0      0  13.00   NaN        S
887         1       1  female  19.0      0      0  30.00   B42        S
888         0       3  female   NaN      1      2  23.45   NaN        S
889         1       1    male  26.0      0      0  30.00  C148        C
890         0       3    male  32.0      0      0   7.75   NaN        Q

     Has_Cabin Deck
886          0  NaN
887          1    B
888          0  NaN
889          1    C
890          0  NaN
     PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare Cabin Embarked
413         1305       3    male   NaN      0      0    8.0500   NaN        S
414         1306       1  female  39.0      0      0  108.9000  C105        C
415         1307       3    male  38.5      0      0    7.2500   NaN        S
416         1308       3    male   NaN      0      0    8.0500   NaN        S
417         1309       3    male   NaN      1      1   22.3583   NaN        C

In [86]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

In [90]:
X = df
y = df2

X_test, X_train, y_test, y_train = train_test_split(X, y, test_size = 0.2, random_state = 40)
print({X_train})
print({X_test})


model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

prediction = model.predict(X_test)

ValueError: Found input variables with inconsistent numbers of samples: [891, 418]

maybe the error is because of x and y have different results